services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: azureflaskapp-server.mysql.database.azure.com
      DB_USER: yzruefqhpn
      DB_PASSWORD: mYw$1vUsZMo0y2Z9
      DB_NAME: azureflaskapp-database


