services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      AZURE_MYSQL_HOST: azureflaskapp-server.mysql.database.azure.com
      AZURE_MYSQL_USER: yzruefqhpn
      AZURE_MYSQL_PASSWORD: mYw$1vUsZMo0y2Z9
      AZURE_MYSQL_NAME: azureflaskapp-database


